In [5]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv("raw/data.csv", delimiter=";")
data.columns = [i.lower().replace(" ", "_").replace("(", "").replace(")", "").replace("\t", "") for i in data.columns]
data.rename(columns={'nacionality': 'nationality'}, inplace=True)
data.head()

,marital_status,application_mode,application_order,course,daytime/evening_attendance,previous_qualification,previous_qualification_grade,nationality,mother's_qualification,father's_qualification,...,curricular_units_2nd_sem_credited,curricular_units_2nd_sem_enrolled,curricular_units_2nd_sem_evaluations,curricular_units_2nd_sem_approved,curricular_units_2nd_sem_grade,curricular_units_2nd_sem_without_evaluations,unemployment_rate,inflation_rate,gdp,target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [7]:
""" #a = "0 - Student 1 - Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers 2 - Specialists in Intellectual and Scientific Activities 3 - Intermediate Level Technicians and Professions 4 - Administrative staff 5 - Personal Services, Security and Safety Workers and Sellers 6 - Farmers and Skilled Workers in Agriculture, Fisheries and Forestry 7 - Skilled Workers in Industry, Construction and Craftsmen 8 - Installation and Machine Operators and Assembly Workers 9 - Unskilled Workers 10 - Armed Forces Professions 90 - Other Situation 99 - (blank) 122 - Health professionals 123 - teachers 125 - Specialists in information and communication technologies (ICT) 131 - Intermediate level science and engineering technicians and professions 132 - Technicians and professionals, of intermediate level of health 134 - Intermediate level technicians from legal, social, sports, cultural and similar services 141 - Office workers, secretaries in general and data processing operators 143 - Data, accounting, statistical, financial services and registry-related operators 144 - Other administrative support staff 151 - personal service workers 152 - sellers 153 - Personal care workers and the like 171 - Skilled construction workers and the like, except electricians 173 - Skilled workers in printing, precision instrument manufacturing, jewelers, artisans and the like 175 - Workers in food processing, woodworking, clothing and other industries and crafts 191 - cleaning workers 192 - Unskilled workers in agriculture, animal production, fisheries and forestry 193 - Unskilled workers in extractive industry, construction, manufacturing and transport 194 - Meal preparation assistants"
a = "0 - Student 1 - Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers 2 - Specialists in Intellectual and Scientific Activities 3 - Intermediate Level Technicians and Professions 4 - Administrative staff 5 - Personal Services, Security and Safety Workers and Sellers 6 - Farmers and Skilled Workers in Agriculture, Fisheries and Forestry 7 - Skilled Workers in Industry, Construction and Craftsmen 8 - Installation and Machine Operators and Assembly Workers 9 - Unskilled Workers 10 - Armed Forces Professions 90 - Other Situation 99 - (blank) 101 - Armed Forces Officers 102 - Armed Forces Sergeants 103 - Other Armed Forces personnel 112 - Directors of administrative and commercial services 114 - Hotel, catering, trade and other services directors 121 - Specialists in the physical sciences, mathematics, engineering and related techniques 122 - Health professionals 123 - teachers 124 - Specialists in finance, accounting, administrative organization, public and commercial relations 131 - Intermediate level science and engineering technicians and professions 132 - Technicians and professionals, of intermediate level of health 134 - Intermediate level technicians from legal, social, sports, cultural and similar services 135 - Information and communication technology technicians 141 - Office workers, secretaries in general and data processing operators 143 - Data, accounting, statistical, financial services and registry-related operators 144 - Other administrative support staff 151 - personal service workers 152 - sellers 153 - Personal care workers and the like 154 - Protection and security services personnel 161 - Market-oriented farmers and skilled agricultural and animal production workers 163 - Farmers, livestock keepers, fishermen, hunters and gatherers, subsistence 171 - Skilled construction workers and the like, except electricians 172 - Skilled workers in metallurgy, metalworking and similar 174 - Skilled workers in electricity and electronics 175 - Workers in food processing, woodworking, clothing and other industries and crafts 181 - Fixed plant and machine operators 182 - assembly workers 183 - Vehicle drivers and mobile equipment operators 192 - Unskilled workers in agriculture, animal production, fisheries and forestry 193 - Unskilled workers in extractive industry, construction, manufacturing and transport 194 - Meal preparation assistants 195 - Street vendors (except food) and street service providers	"
a = a.replace(" - ", ":").replace("; ", ",").replace(" ", "_")
a = a.lower()
a """

' #a = "0 - Student 1 - Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers 2 - Specialists in Intellectual and Scientific Activities 3 - Intermediate Level Technicians and Professions 4 - Administrative staff 5 - Personal Services, Security and Safety Workers and Sellers 6 - Farmers and Skilled Workers in Agriculture, Fisheries and Forestry 7 - Skilled Workers in Industry, Construction and Craftsmen 8 - Installation and Machine Operators and Assembly Workers 9 - Unskilled Workers 10 - Armed Forces Professions 90 - Other Situation 99 - (blank) 122 - Health professionals 123 - teachers 125 - Specialists in information and communication technologies (ICT) 131 - Intermediate level science and engineering technicians and professions 132 - Technicians and professionals, of intermediate level of health 134 - Intermediate level technicians from legal, social, sports, cultural and similar services 141 - Office workers, secretaries in general and data processing operators 143 - Data, accounting, statistical, financial services and registry-related operators 144 - Other administrative support staff 151 - personal service workers 152 - sellers 153 - Personal care workers and the like 171 - Skilled construction workers and the like, except electricians 173 - Skilled workers in printing, precision instrument manufacturing, jewelers, artisans and the like 175 - Workers in food processing, woodworking, clothing and other industries and crafts 191 - cleaning workers 192 - Unskilled workers in agriculture, animal production, fisheries and forestry 193 - Unskilled workers in extractive industry, construction, manufacturing and transport 194 - Meal preparation assistants"\na = "0 - Student 1 - Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers 2 - Specialists in Intellectual and Scientific Activities 3 - Intermediate Level Technicians and Professions 4 - Administrative staff 5 - Personal Services, Security and Safety Workers and Sellers 6 - Farmers and Skilled Workers in Agriculture, Fisheries and Forestry 7 - Skilled Workers in Industry, Construction and Craftsmen 8 - Installation and Machine Operators and Assembly Workers 9 - Unskilled Workers 10 - Armed Forces Professions 90 - Other Situation 99 - (blank) 101 - Armed Forces Officers 102 - Armed Forces Sergeants 103 - Other Armed Forces personnel 112 - Directors of administrative and commercial services 114 - Hotel, catering, trade and other services directors 121 - Specialists in the physical sciences, mathematics, engineering and related techniques 122 - Health professionals 123 - teachers 124 - Specialists in finance, accounting, administrative organization, public and commercial relations 131 - Intermediate level science and engineering technicians and professions 132 - Technicians and professionals, of intermediate level of health 134 - Intermediate level technicians from legal, social, sports, cultural and similar services 135 - Information and communication technology technicians 141 - Office workers, secretaries in general and data processing operators 143 - Data, accounting, statistical, financial services and registry-related operators 144 - Other administrative support staff 151 - personal service workers 152 - sellers 153 - Personal care workers and the like 154 - Protection and security services personnel 161 - Market-oriented farmers and skilled agricultural and animal production workers 163 - Farmers, livestock keepers, fishermen, hunters and gatherers, subsistence 171 - Skilled construction workers and the like, except electricians 172 - Skilled workers in metallurgy, metalworking and similar 174 - Skilled workers in electricity and electronics 175 - Workers in food processing, woodworking, clothing and other industries and crafts 181 - Fixed plant and machine operators 182 - assembly workers 183 - Vehicle drivers and mobile equipment operators 192 - Unskilled workers in agriculture, animal production, fisheries and forestry 193 - Unskilled workers in extractive industry, construction, manufacturing and transport 194 - Meal preparation assistants 195 - Street vendors (except food) and street service providers\t"\na = a.replace(" - ", ":").replace("; ", ",").replace(" ", "_")\na = a.lower()\na '

In [8]:
dict_occupation_mother = {0:"student",
                          1:"representatives_of_the_legislative_power_and_executive_bodies_directors_directors_and_executive_managers",
                          2:"specialists_in_intellectual_and_scientific_activities",
                          3:"intermediate_level_technicians_and_professions",
                          4:"administrative_staff",
                          5:"personal_services_security_and_safety_workers_and_sellers",
                          6:"farmers_and_skilled_workers_in_agriculture_fisheries_and_forestry",
                          7:"skilled_workers_in_industry_construction_and_craftsmen",
                          8:"installation_and_machine_operators_and_assembly_workers",
                          9:"unskilled_workers",
                          10:"armed_forces_professions",
                          90:"other_situation",
                          99:"blank",
                          122:"health_professionals",
                          123:"teachers",
                          125:"Specialists in information and communication technologies (ICT)",
                          131:"intermediate_level_science_and_engineering_technicians_and_professions",
                          132:"technicians_and_professionals_of_intermediate_level_of_health",
                          134:"intermediate_level_technicians_from_legal_social_sports_cultural_and_similar_services",
                          141:"office_workers_secretaries_in_general_and_data_processing_operators",
                          143:"data_accounting_statistical_financial_services_and_registry-related_operators",
                          144:"other_administrative_support_staff",
                          151:"personal_service_workers",
                          152:"sellers",
                          153:"personal_care_workers_and_the_like",
                          171:"skilled_construction_workers_and_the_like_except_electricians",
                          173:"Skilled workers in printing, precision instrument manufacturing, jewelers, artisans and the like",
                          175:"workers_in_food_processing_woodworking_clothing_and_other_industries_and_crafts",
                          191:"cleaning workers",
                          192:"unskilled_workers_in_agriculture_animal_production_fisheries_and_forestry",
                          193:"unskilled_workers_in_extractive_industry_construction_manufacturing_and_transport",
                          194:"meal_preparation_assistants"
                          }

dict_occupation_father = {0:"student",
                          1:"representatives_of_the_legislative_power_and_executive_bodies_directors_directors_and_executive_managers",
                          2:"specialists_in_intellectual_and_scientific_activities",
                          3:"intermediate_level_technicians_and_professions",
                          4:"administrative_staff",
                          5:"personal_services_security_and_safety_workers_and_sellers",
                          6:"farmers_and_skilled_workers_in_agriculture_fisheries_and_forestry",
                          7:"skilled_workers_in_industry_construction_and_craftsmen",
                          8:"installation_and_machine_operators_and_assembly_workers",
                          9:"unskilled_workers",
                          10:"armed_forces_professions",
                          90:"other_situation",
                          99:"blank",
                          101:"armed_forces_officers",
                          102:"armed_forces_sergeants",
                          103:"other_armed_forces_personnel",
                          112:"directors_of_administrative_and_commercial_services",
                          114:"hotel_catering_trade_and_other_services_directors",
                          121:"specialists_in_the_physical_sciences_mathematics_engineering_and_related_techniques",
                          122:"health_professionals",
                          123:"teachers",
                          124:"specialists_in_finance_accounting_administrative_organization_public_and_commercial_relations",
                          131:"intermediate_level_science_and_engineering_technicians_and_professions",
                          132:"technicians_and_professionals_of_intermediate_level_of_health",
                          134:"intermediate_level_technicians_from_legal_social_sports_cultural_and_similar_services",
                          135:"information_and_communication_technology_technicians",
                          141:"office_workers_secretaries_in_general_and_data_processing_operators",
                          143:"data_accounting_statistical_financial_services_and_registry-related_operators",
                          144:"other_administrative_support_staff",
                          151:"personal_service_workers",
                          152:"sellers",
                          153:"personal_care_workers_and_the_like",
                          154:"protection_and_security_services_personnel",
                          161:"market-oriented_farmers_and_skilled_agricultural_and_animal_production_workers",
                          163:"farmers_livestock_keepers_fishermen_hunters_and_gatherers_subsistence",
                          171:"skilled_construction_workers_and_the_like_except_electricians",
                          172:"skilled_workers_in_metallurgy_metalworking_and_similar",
                          174:"skilled_workers_in_electricity_and_electronics",
                          175:"workers_in_food_processing_woodworking_clothing_and_other_industries_and_crafts",
                          181:"fixed_plant_and_machine_operators",
                          182:"assembly_workers",
                          183:"vehicle_drivers_and_mobile_equipment_operators",
                          192:"unskilled_workers_in_agriculture_animal_production_fisheries_and_forestry",
                          193:"unskilled_workers_in_extractive_industry_construction_manufacturing_and_transport",
                          194:"meal_preparation_assistants",
                          195:"street_vendors_except_food_and_street_service_providers"
                          }

dict_qualifications_mother = {1:"secondary_education_12th_year_of_schooling_or_eq",
                              2:"higher_education_bachelors_degree",
                              3:"higher_education_degree",
                              4:"higher_education_masters",
                              5:"higher_education_doctorate",
                              6:"frequency_of_higher_education",
                              9:"12th_year_of_schooling_not_completed",
                              10:"11th_year_of_schooling_not_completed",
                              11:"7th_year_(old)",
                              12:"other_11th_year_of_schooling", 
                              14:"10th_year_of_schooling",
                              18:"general_commerce_course",
                              19:"basic_education_3rd_cycle_(9th/10th/11th year)_or_equiv",
                              22:"technical-professional_course",
                              26:"7th_year_of_schooling",
                              27:"2nd_cycle_of_the_general_high_school_course",
                              29:"9th_year_of_schooling_not_completed",
                              30:"8th_year_of_schooling",
                              34:"unknown",
                              35:"can't_read_or_write",
                              36:"can_read_without_having_a_4th_year_of_schooling",
                              37:"basic_education_1st_cycle_(4th/5th_year)_or_equiv",
                              38:"basic_education_2nd_cycle_(6th/7th/8th year)_or_equiv",
                              39:"technological_specialization_course",
                              40:"higher_education_degree_1st_cycle",
                              41:"specialized_higher_studies_course",
                              42:"professional_higher_technical_course",
                              43:"higher_education_master_2nd_cycle",
                              44:"higher_education:doctorate_3rd_cycle",
                              }

dict_qualifications_father = {1:"secondary_education_12th_year_of_schooling_or_eq",
                              2:"higher_education_bachelors_degree",
                              3:"higher_education_degree",
                              4:"higher_education_masters",
                              5:"higher_education_doctorate",
                              6:"frequency_of_higher_education",
                              9:"12th_year_of_schooling_not_completed",
                              10:"11th_year_of_schooling_not_completed",
                              11:"7th_year_(old)",
                              12:"other_11th_year_of_schooling",
                              13:"2nd_year_complementary_high_school_course",  
                              14:"10th_year_of_schooling",
                              18:"general_commerce_course",
                              19:"basic_education_3rd_cycle_(9th/10th/11th year)_or_equiv",
                              20:"complementary_high_school_course",
                              22:"technical-professional_course",
                              25:"complementary_high_school_course_not_concluded",
                              26:"7th_year_of_schooling",
                              27:"2nd_cycle_of_the_general_high_school_course",
                              29:"9th_year_of_schooling_not_completed",
                              30:"8th_year_of_schooling",
                              31:"general_course_of_administration_and_commerce",
                              33:"supplementary_accounting_and_administration",
                              34:"unknown",
                              35:"can't_read_or_write",
                              36:"can_read_without_having_a_4th_year_of_schooling",
                              37:"basic_education_1st_cycle_(4th/5th_year)_or_equiv",
                              38:"basic_education_2nd_cycle_(6th/7th/8th year)_or_equiv",
                              39:"technological_specialization_course",
                              40:"higher_education_degree_1st_cycle",
                              41:"specialized_higher_studies_course",
                              42:"professional_higher_technical_course",
                              43:"higher_education_master_2nd_cycle",
                              44:"higher_education:doctorate_3rd_cycle",
                              }

dict_nationality = {1:"portuguese",
                    2:"german",
                    6:"spanish",
                    11:"italian",
                    13:"dutch",
                    14:"english",
                    17:"lithuanian",
                    21:"angolan",
                    22:"cape_verdean",
                    24:"guinean",
                    25:"mozambican",
                    26:"santomean",
                    32:"turkish",
                    41:"brazilian",
                    62:"romanian",
                    100:"moldova",
                    101:"mexican",
                    103:"ukrainian",
                    105:"russian",
                    108:"cuban",
                    109:"colombian"
                    }

dict_previous_education = {1:"secondary_education",
                           2:"higher_education_bachelors_degree",
                           3:"higher_education_degree",
                           4:"higher_education_masters",
                           5:"higher_education_doctorate",
                           6:"frequency_of_higher_education",
                           9:"12th_year_of_schooling_not_completed",
                           10:"11th_year_of_schooling_not_completed",
                           12:"other_11th_year_of_schooling", 
                           14:"10th_year_of_schooling",
                           15:"10th_year_of_schooling_not_completed",
                           19:"basic_education_3rd_cycle_(9th/10th/11th year)_or_equiv",
                           38:"basic_education_2nd_cycle_(6th/7th/8th year)_or_equiv",
                           39:"technological_specialization_course",
                           40:"higher_education_degree_1st_cycle",
                           42:"professional_higher_technical_course",
                           43:"higher_education_master_2nd_cycle"
                           }

dict_course = {33:"biofuel_production_technologies",
               171:"animation_and_multimedia_design",
               8014:"social_service_evening_attendance",
               9003:"agronomy",
               9070:"communication_design",
               9085:"veterinary_nursing",
               9119:"informatics_engineering",
               9130:"equinculture",
               9147:"management",
               9238:"social_service",
               9254:"tourism",
               9500:"nursing",
               9556:"oral_hygiene",
               9670:"advertising_and_marketing_management",
               9773:"journalism_and_communication",
               9853:"basic_education",
               9991:"management_evening_attendance"
               }

dict_marital_status = {1:"single", 
                       2:"married",
                       3:"widower",
                       4:"divorced",
                       5:"facto union",
                       6:"legally separated"
                       }

dict_application_mode = {1:"1st_phase_general_contingent",
                         2:"ordinance_no_612_93",
                         5:"1st_phase_special_contingent_azores_island",
                         7:"holders_of_other_higher_courses",
                         10:"ordinance_no_854B_99",
                         15:"international_student_bachelor",
                         16:"1st_phase_special_contingent_madeira_island",
                         17:"2nd_phase_general_contingent",
                         18:"3rd_phase_general_contingent",
                         26:"ordinance_no_533A_99_item_b2_different_plan",
                         27:"ordinance_no_533A_99_item_b3_other_institution",
                         39:"over_23_years_old",
                         42:"transfer",
                         43:"change_of_course",
                         44:"technological_specialization_diploma_holders",
                         51:"change_of_institution_course",
                         53:"short_cycle_diploma_holders",
                         57:"change_of_institution_course_international"
                         }

In [9]:
dicts = [dict_marital_status,
         dict_application_mode,
         dict_course,
         dict_previous_education,
         dict_nationality,
         dict_occupation_mother,
         dict_occupation_father,
         dict_qualifications_mother,
         dict_qualifications_father
         ]
columns_to_replace = ['marital_status',
                      'application_mode',
                      'course',
                      'previous_qualification',
                      'nationality',
                      "mother's_occupation",
                      "father's_occupation",
                      "mother's_qualification",
                      "father's_qualification"
                      ]

for i,j in enumerate(columns_to_replace):
    data[columns_to_replace[i]] = data[columns_to_replace[i]].replace(dicts[i])

data

,marital_status,application_mode,application_order,course,daytime/evening_attendance,previous_qualification,previous_qualification_grade,nationality,mother's_qualification,father's_qualification,...,curricular_units_2nd_sem_credited,curricular_units_2nd_sem_enrolled,curricular_units_2nd_sem_evaluations,curricular_units_2nd_sem_approved,curricular_units_2nd_sem_grade,curricular_units_2nd_sem_without_evaluations,unemployment_rate,inflation_rate,gdp,target
0,single,2nd_phase_general_contingent,5,animation_and_multimedia_design,1,secondary_education,122.0,portuguese,basic_education_3rd_cycle_(9th/10th/11th year)...,other_11th_year_of_schooling,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,single,international_student_bachelor,1,tourism,1,secondary_education,160.0,portuguese,secondary_education_12th_year_of_schooling_or_eq,higher_education_degree,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,single,1st_phase_general_contingent,5,communication_design,1,secondary_education,122.0,portuguese,basic_education_1st_cycle_(4th/5th_year)_or_equiv,basic_education_1st_cycle_(4th/5th_year)_or_equiv,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,single,2nd_phase_general_contingent,2,journalism_and_communication,1,secondary_education,122.0,portuguese,basic_education_2nd_cycle_(6th/7th/8th year)_o...,basic_education_1st_cycle_(4th/5th_year)_or_equiv,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,married,over_23_years_old,1,social_service_evening_attendance,0,secondary_education,100.0,portuguese,basic_education_1st_cycle_(4th/5th_year)_or_equiv,basic_education_2nd_cycle_(6th/7th/8th year)_o...,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,single,1st_phase_general_contingent,6,journalism_and_communication,1,secondary_education,125.0,portuguese,secondary_education_12th_year_of_schooling_or_eq,secondary_education_12th_year_of_schooling_or_eq,...,0,6,8,5,12.666667,0,15.5,2.8,-4.06,Graduate
4420,single,1st_phase_general_contingent,2,journalism_and_communication,1,secondary_education,120.0,russian,secondary_education_12th_year_of_schooling_or_eq,secondary_education_12th_year_of_schooling_or_eq,...,0,6,6,2,11.000000,0,11.1,0.6,2.02,Dropout
4421,single,1st_phase_general_contingent,1,nursing,1,secondary_education,154.0,portuguese,basic_education_1st_cycle_(4th/5th_year)_or_equiv,basic_education_1st_cycle_(4th/5th_year)_or_equiv,...,0,8,9,1,13.500000,0,13.9,-0.3,0.79,Dropout
4422,single,1st_phase_general_contingent,1,management,1,secondary_education,180.0,portuguese,basic_education_1st_cycle_(4th/5th_year)_or_equiv,basic_education_1st_cycle_(4th/5th_year)_or_equiv,...,0,5,6,5,12.000000,0,9.4,-0.8,-3.12,Graduate
4423,single,ordinance_no_854B_99,1,journalism_and_communication,1,secondary_education,152.0,cape_verdean,basic_education_2nd_cycle_(6th/7th/8th year)_o...,basic_education_1st_cycle_(4th/5th_year)_or_equiv,...,0,6,6,6,13.000000,0,12.7,3.7,-1.70,Graduate

In [10]:
# Define different 'class' of occupations

# Blue-Collar: 'Working class', primarily manual labour.
# Light-Blue_collar: Atisans. For example, jewelrer. 
# White-Collar: Salaried professional, primarily office worker.
# Gold-Collar: Specialised work. Doctors, lawyers, engineers, pilots, scientists.
# Pink-Collar: Nurse, secretary, elementary school teacher, 'traditionally female occupations' - generally encompases service-focused occupations.
# Grey-Collar: Arbitray label used to designate occupations related to armed forces, or similar

dict_collars = {"blue":['cleaning workers',
                        'farmers_and_skilled_workers_in_agriculture_fisheries_and_forestry',
                        'farmers_livestock_keepers_fishermen_hunters_and_gatherers_subsistence',
                        'market-oriented_farmers_and_skilled_agricultural_and_animal_production_workers',
                        'installation_and_machine_operators_and_assembly_workers',
                        'unskilled_workers',
                        'unskilled_workers_in_agriculture_animal_production_fisheries_and_forestry',
                        'unskilled_workers_in_extractive_industry_construction_manufacturing_and_transport',
                        'assembly_workers',
                        'fixed_plant_and_machine_operators',
                        'vehicle_drivers_and_mobile_equipment_operators',
                        'skilled_construction_workers_and_the_like_except_electricians',
                        'skilled_workers_in_industry_construction_and_craftsmen',
                        'skilled_workers_in_electricity_and_electronics',
                        'skilled_workers_in_metallurgy_metalworking_and_similar'
                        ],
                "light-blue":['Skilled workers in printing, precision instrument manufacturing, jewelers, artisans and the like',
                              'workers_in_food_processing_woodworking_clothing_and_other_industries_and_crafts'
                              ],
                "white":['administrative_staff',
                         'health_professionals',
                         'intermediate_level_science_and_engineering_technicians_and_professions',
                         'intermediate_level_technicians_and_professions',
                         'intermediate_level_technicians_from_legal_social_sports_cultural_and_similar_services',
                         'office_workers_secretaries_in_general_and_data_processing_operators',
                         'other_administrative_support_staff', 
                         'representatives_of_the_legislative_power_and_executive_bodies_directors_directors_and_executive_managers',
                         'technicians_and_professionals_of_intermediate_level_of_health',
                         'data_accounting_statistical_financial_services_and_registry-related_operators',
                         'directors_of_administrative_and_commercial_services',
                         'information_and_communication_technology_technicians',
                         'sellers'
                         ],
                "pink":['meal_preparation_assistants',
                        'personal_care_workers_and_the_like', 
                        'personal_service_workers',
                        'personal_services_security_and_safety_workers_and_sellers',
                        'teachers',
                        'hotel_catering_trade_and_other_services_directors'
                        ],
                "gold":['Specialists in information and communication technologies (ICT)',
                        'specialists_in_intellectual_and_scientific_activities',
                        'specialists_in_finance_accounting_administrative_organization_public_and_commercial_relations',
                        'specialists_in_the_physical_sciences_mathematics_engineering_and_related_techniques'
                        ],
                "other":['blank',
                         'other_situation',
                         'student',
                         'street_vendors_except_food_and_street_service_providers'
                         ],
                "gray":['armed_forces_professions',
                         'armed_forces_officers',
                         'armed_forces_sergeants',
                         'other_armed_forces_personnel',
                         'protection_and_security_services_personnel']
                }

In [11]:
inverse = { v: k for k, l in dict_collars.items() for v in l }

In [15]:
#[job for job in np.unique((data["father's_occupation"])) if job not in np.unique((data["mother's_occupation"]))]

np.unique((data["father's_qualification"]))

[job for job in np.unique((data["father's_qualification"])) if job not in np.unique((data["mother's_qualification"]))]

['2nd_year_complementary_high_school_course',
 'complementary_high_school_course',
 'complementary_high_school_course_not_concluded',
 'general_course_of_administration_and_commerce',
 'supplementary_accounting_and_administration']

In [16]:
# Create groupings for education (to reduce feature space)
#https://eurydice.eacea.ec.europa.eu/national-education-systems/portugal/overview#:~:text=The%20Portuguese%20education%20system%20is%20divided%20in%20pre%2Dschool%20education,15%20to%2018%20years%20old).

# 
# Upper secondary: Grades 10, 11, 12

dict_education = {  "basic":[   '7th_year_(old)',
                                '7th_year_of_schooling',
                                '8th_year_of_schooling',
                                '9th_year_of_schooling_not_completed',
                                'basic_education_1st_cycle_(4th/5th_year)_or_equiv',
                                'basic_education_2nd_cycle_(6th/7th/8th year)_or_equiv'
                                ],
                    "upper_secondary":[ '10th_year_of_schooling',
                                                '11th_year_of_schooling_not_completed',
                                                '12th_year_of_schooling_not_completed',
                                                '2nd_cycle_of_the_general_high_school_course',
                                                'other_11th_year_of_schooling',
                                                'secondary_education_12th_year_of_schooling_or_eq',
                                                'basic_education_3rd_cycle_(9th/10th/11th year)_or_equiv',
                                                '2nd_year_complementary_high_school_course',
                                                'complementary_high_school_course',
                                                'complementary_high_school_course_not_concluded'
                                                ],
                    "higher_education_bac":['higher_education_bachelors_degree', 
                                            'higher_education_degree',
                                            'higher_education_degree_1st_cycle',],
                    "higher_education_mas":['higher_education_master_2nd_cycle', 
                                            'higher_education_masters'],
                    "higher_education_doc":['higher_education:doctorate_3rd_cycle',
                                            'higher_education_doctorate',],
                    "other":['general_commerce_course',
                             'technological_specialization_course',
                             'technical-professional_course',
                             'specialized_higher_studies_course',
                             'frequency_of_higher_education',
                             'professional_higher_technical_course',
                             'general_course_of_administration_and_commerce',
                             'supplementary_accounting_and_administration'],
                    "low_education":["can't_read_or_write", 
                                   'can_read_without_having_a_4th_year_of_schooling',]
                    }

#['unknown']
inverse_education = { v: k for k, l in dict_education.items() for v in l }

In [17]:
#data[columns_to_replace[i]] = data[columns_to_replace[i]].replace(dicts[i])

data["mother's_occupation"] = data["mother's_occupation"].replace(inverse)
data["father's_occupation"] = data["father's_occupation"].replace(inverse)
data["mother's_qualification"] = data["mother's_qualification"].replace(inverse_education)
data["father's_qualification"] = data["father's_qualification"].replace(inverse_education)
data.iloc[:, 5:]

,previous_qualification,previous_qualification_grade,nationality,mother's_qualification,father's_qualification,mother's_occupation,father's_occupation,admission_grade,displaced,educational_special_needs,...,curricular_units_2nd_sem_credited,curricular_units_2nd_sem_enrolled,curricular_units_2nd_sem_evaluations,curricular_units_2nd_sem_approved,curricular_units_2nd_sem_grade,curricular_units_2nd_sem_without_evaluations,unemployment_rate,inflation_rate,gdp,target
0,secondary_education,122.0,portuguese,upper_secondary,upper_secondary,pink,blue,127.3,1,0,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,secondary_education,160.0,portuguese,upper_secondary,higher_education_bac,white,white,142.5,1,0,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,secondary_education,122.0,portuguese,basic,basic,blue,blue,124.8,1,0,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,secondary_education,122.0,portuguese,basic,basic,pink,white,119.6,1,0,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,secondary_education,100.0,portuguese,basic,basic,blue,blue,141.5,0,0,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,secondary_education,125.0,portuguese,upper_secondary,upper_secondary,pink,white,122.2,0,0,...,0,6,8,5,12.666667,0,15.5,2.8,-4.06,Graduate
4420,secondary_education,120.0,russian,upper_secondary,upper_secondary,blue,blue,119.0,1,0,...,0,6,6,2,11.000000,0,11.1,0.6,2.02,Dropout
4421,secondary_education,154.0,portuguese,basic,basic,blue,blue,149.5,1,0,...,0,8,9,1,13.500000,0,13.9,-0.3,0.79,Dropout
4422,secondary_education,180.0,portuguese,basic,basic,blue,white,153.8,1,0,...,0,5,6,5,12.000000,0,9.4,-0.8,-3.12,Graduate
4423,secondary_education,152.0,cape_verdean,basic,basic,pink,blue,152.0,1,0,...,0,6,6,6,13.000000,0,12.7,3.7,-1.70,Graduate

# How does the inclusions/exclusion of protected features affect the signal of whether an individual will drop out or not

* Perhaps stick with 1 or 2 models (perhaps 1 that only recognizes linear relationships, and another than can address more complex traits), and curate different datasets
* More dabiasing methods is more interesting than more models
* Explainability is very important for this type of study
* Ethical dilemma - the duty of not taking the protected features into account (it is the "right thing" to not discriminate based on socio-economic status), but it can also be used to help people in need (identifying low-income people in need to help) - The other goal could also be to reject applicants at risk of dropping out.
* ## How does the use-case of such a model dictate the features to be used, and the protections that could/should/might be applied
* Is there a risk that we find some sort of random result from shuffling features around???